services:

  art-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      ART_DB_URL: ${ART_DB_URL}
      RUNNING_IN_DOCKER: "true"
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
    networks:
      - apollo-net


  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - apollo-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
    ports:
      - "8080:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - apollo-net

  test-artwork:
    build: .
    command: >
      bash -c "go test ./internal/test/integration_test/artwork_test.go"
    environment:
      ART_DB_URL: ${ART_DB_URL}
      RUNNING_IN_DOCKER: "true"
    depends_on:
      - db
    networks:
      - apollo-net

  # test-middleware:
  #   build: .
  #   command: >
  #     bash -c "go test ./internal/test/integration_test/middleware_test.go"
  #   environment:
  #     ART_DB_URL: ${ART_DB_URL}
  #     RUNNING_IN_DOCKER: "true"
  #   depends_on:
  #     - db
  #   networks:
  #     - apollo-net

networks:
  apollo-net:
    driver: bridge

volumes:
  db-data:
  keycloak-data:
