name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.8  

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: go mod tidy

      # Step 4: Run tests
      - name: Run Tests
        run: go test ./... -v

  security:
    name: Run Security Scans
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.8  

      # Step 3: Install Gosec
      - name: Install Gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      # Step 4: Run Gosec
      - name: Run Gosec
        run: gosec ./...

      # Step 5: Install govulncheck
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      # Step 6: Run govulncheck
      - name: Run govulncheck
        run: govulncheck ./... 
  
